"""Dados de exemplo e limites reutilizados pela suíte de testes."""

NOME_CAVALO = "Relâmpago"
RACA_CAVALO = "MANGA-LARGA MARCHADOR"
RACA_CAVALO_MINUSCULA = RACA_CAVALO.lower()
RACA_INVALIDA = "INVALIDA"
IDADE_CAVALO = 5
PESO_CAVALO = 450.0
SEXO_CAVALO = "MACHO"
DATA_NASCIMENTO_CAVALO = "2021-01-01"

NOME_ESTABULO = "Estábulo Central"
LOCALIZACAO_ESTABULO = "Fazenda Verde"
CAPACIDADE_ESTABULO_10 = 10
CAPACIDADE_ESTABULO_MINIMA = 1

ROTA_EQUINOS = "/equinos"
ROTA_ESTABULOS = "/estabulos"
ROTA_HEALTH = "/health"
STATUS_CRIADO = 201
STATUS_OK = 200
STATUS_ERRO_REGRA = 400
STATUS_ERRO_VALIDACAO = 422
ID_INEXISTENTE = "id-inexistente"
ID_EQUINO_TESTE = "equino-teste"
ID_OUTRO_EQUINO_TESTE = "outro-equino-teste"
ID_ESTABULO_TESTE = "estabulo-teste"
TEXTO_VAZIO = ""
NOME_COM_UM_CARACTERE = "A"
NOME_COM_200_CARACTERES = "A" * 200
NOME_COM_201_CARACTERES = "A" * 201
IDADE_MINIMA_PERMITIDA = 0
IDADE_ACIMA_DA_MINIMA = 1
IDADE_INVALIDA = -1
CAPACIDADE_INVALIDA = 0
SEXO_INVALIDO = "INVALIDO"
ERRO_SERVICO_SIMULADO = "erro simulado do serviço"

LOCALE_FAKER = "pt_BR"
PREFIXO_ID_EQUINO = "EQU"
PREFIXO_ID_ESTABULO = "EST"
ID_ALEATORIO_MINIMO = 1000
ID_ALEATORIO_MAXIMO = 9999
IDADE_ALEATORIA_MINIMA = 1
IDADE_ALEATORIA_MAXIMA = 20
PESO_ALEATORIO_MINIMO = 300.0
PESO_ALEATORIO_MAXIMO = 600.0
CASAS_DECIMAIS_PESO = 2
CAPACIDADE_ALEATORIA_MINIMA = 1
CAPACIDADE_ALEATORIA_MAXIMA = 50
SEXOS_VALIDOS = ("MACHO", "FEMEA")
RACAS_VALIDAS = (
    RACA_CAVALO,
    "QUARTO DE MILHA",
    "ANDALUZ",
    "LUSITANO",
)
